[workspace]
members = [
    "solana-client-gen",
    "common",
    "common/tests",
    "crank",
    "safe",
    "registry",
    "node",
    "node/json-rpc",
    "node/logging",
    "node/crank",
    "node/registry",
    "node/context",
]
exclude = [
    "dex",
    "registry/program",
    "rewards/constant",
    "safe/program",
]
