[package]
name = "serum-pool-schema"
version = "0.1.0"
authors = ["Sebastian Conybeare <sebastian@projectserum.com>"]
edition = "2018"

[features]
program = ["solana-sdk/program"]
default = ["solana-sdk/default"]

[dependencies]
borsh = "0.7.1"
solana-sdk = { version = "1.3.9", default-features = false }

[[bin]]
name = "print-schema"
path = "src/print-schema.rs"
